# Generated by Django 4.2.5 on 2023-10-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=500)),
                ('detalle_corto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('S', 'SUSPENSION_ACTIVIDADES'), ('C', 'SUSPENSION_CLASE INFORMACION'), ('T', 'Informacion')], default='S', max_length=1)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_ultima_modificacion', models.DateTimeField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USM_WEB.entidad')),
            ],
        ),
    ]
