# Generated by Django 4.2.5 on 2023-10-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USM_WEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='USM_WEB/static/USM_WEB/img/logo_entidad/'),
        ),
    ]
